import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "var(--background)",
        foreground: "var(--text-primary)",
        primary: {
          DEFAULT: "var(--primary-color)",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "var(--secondary-color)",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "var(--accent-color)",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "card-bg": "var(--card-bg)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      minWidth: {
        "24": "6rem",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    "bg-primary",
    "bg-opacity-10",
    "bg-opacity-20",
    "bg-opacity-30",
    "bg-opacity-40",
    "bg-opacity-50",
    "bg-opacity-80",
    "bg-opacity-90",
    "bg-opacity-95",
    "text-primary",
    "border-primary",
    "border-opacity-30",
    "border-opacity-50",
    "hover:border-primary",
    "hover:border-opacity-50",
    "bg-green-500",
    "bg-opacity-10",
    "border-green-500",
    "border-opacity-30",
    "bg-red-500",
    "bg-opacity-10",
    "border-red-500",
    "border-opacity-30",
    "from-primary",
    "to-accent",
    "from-background",
    "via-background",
    "to-primary",
    "bg-gradient-to-r",
    "bg-gradient-to-br",
    "hover:from-primary",
    "hover:to-accent",
    "hover:bg-gradient-to-r",
    "text-white",
    "text-text-primary",
    "text-text-secondary",
    "bg-background",
    "bg-card-bg",
    "border-gray-700",
    "border-gray-800",
    "border-gray-600",
    "border-white",
    "shadow-xl",
    "shadow-2xl",
    "hover:shadow-2xl",
    "hover:scale-105",
    "hover:scale-110",
    "backdrop-blur-sm",
    "backdrop-blur-md",
    "backdrop-blur-xl",
    "rounded-lg",
    "rounded-xl",
    "rounded-2xl",
    "rounded-full",
    "transition-all",
    "duration-300",
    "duration-500",
    "animate-pulse",
    "delay-1000",
    "delay-2000",
  ],
}
export default config
